# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

title: Eloi Torrents #Accessed via {{site.title}}
email: eloi@eloitorrents.cat
description: >-
    Teoria de nombres, idiomes i programació.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eloitorrents.cat"
github_username:  Eloitor

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-katex

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "ca/"
    values:
      language: "ca"
  - scope:
      path: "en/"
    values:
      language: "en/"
kramdown:
  math_engine: null
  #  html_to_native: true

#katex:
#   js_path: "{{ Gem::lib_path }}/assets/js"  # Path used to search for katex.min.js
#  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    #    throw_error: true
    #error_color: "#cc0000"

# Excuded items by default:
# exclude:
#   - .sass-cache/
#   - gemfiles/
#   - Gemfile
#   - .jekyll-cache/
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Can be overriten by:
# include: ['.htaccess']
