version: 2.1

jobs:
  build:
    docker:
      - image: eloitor/pandoc-make
    resource_class: small
    steps:
      - checkout
      - run: make
      - run: make

workflows:
  welcome:
    jobs:
      - build
