version: 2.1

jobs:
  build:
    docker:
      - image: eloitor/pandoc-make
    resource_class: small
    steps:
      - restore_cache:
          key: v1-my-app  # match any keys *starting with* 'v1-my-app'
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git pull --rebase origin main
#     - checkout
      - run: make
      - run: make
      - save_cache:
           name: kdkd
           key: v1-my-app-{{ .BuildNum }}  # save the latest changes
           paths:
             - .

workflows:
  welcome:
    jobs:
      - build
