# This is a basic workflow to help you get started with Actions

name: Build and publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies # make and pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y make pandoc rsync
      - uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Save build files
        uses: actions/upload-artifact@v2
        with:
          name: My_artifact
          path: web/*
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.github_token }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ./web # The folder the action should deploy.
          single-commit: "true"
